language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t abhilashdk2018/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true abhilashdk2018/docker-react npm run test