language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t abhilashdk2018/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true abhilashdk2018/docker-react npm run test
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react-abhilashdk2019"
  env: "DockerReactAbhilashdk2019-env"
  bucket_name: "elasticbeanstalk-ap-south-1-080499876072"
  bucket_path: "docker-react-abhilashdk2019"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY